# Generated by Django 3.2 on 2023-06-25 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderID', models.AutoField(primary_key=True, serialize=False)),
                ('TableID', models.IntegerField(default=0)),
                ('CompleteStatus', models.BooleanField(default=False)),
                ('DishAmount', models.IntegerField(default=0)),
                ('TablePrice', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='CategoryID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='OrderDish',
            fields=[
                ('OrderDishID', models.AutoField(primary_key=True, serialize=False)),
                ('DishAmount', models.IntegerField(default=1)),
                ('DishPrice', models.FloatField(default=0)),
                ('DishForeignID', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.dish')),
                ('OrderForeignID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
            ],
        ),
    ]
