# Generated by Django 3.2 on 2023-07-14 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_orderdetail_dishforeignid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='DishForeignID',
            new_name='DishID',
        ),
        migrations.RenameField(
            model_name='orderdetail',
            old_name='OrderForeignID',
            new_name='OrderID',
        ),
        migrations.RenameField(
            model_name='ordertable',
            old_name='TotalAmoubnt',
            new_name='TotalAmount',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='Comment',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='End_CookTime',
        ),
        migrations.RemoveField(
            model_name='orderdetail',
            name='Start_CookTime',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='OrderComment',
        ),
    ]
