# Generated by Django 3.2 on 2023-07-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230714_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='OrderDetailID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
