# Generated by Django 3.2 on 2023-07-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_orderdetail_orderdetailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='OrderDetailID',
            field=models.IntegerField(default=8531, primary_key=True, serialize=False, unique=True),
        ),
    ]
