# Generated by Django 3.2 on 2023-07-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_orderdetail_orderdetailid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='OrderDetailID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
