# Generated by Django 3.2 on 2023-07-15 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_orderdetail_orderdetailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='DishList',
            field=models.JSONField(default='This is NULL'),
        ),
    ]
