# Generated by Django 3.2 on 2023-07-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_orderdetail_dishlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='DishList',
            field=models.JSONField(default=list),
        ),
    ]
