# Generated by Django 3.2 on 2023-07-15 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_orderdetail_dishlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='DishList',
        ),
        migrations.AddField(
            model_name='ordertable',
            name='DishList',
            field=models.JSONField(default=list),
        ),
    ]
