# Generated by Django 3.2 on 2023-07-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20230715_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderdetail',
            name='DishPrices',
        ),
        migrations.RemoveField(
            model_name='ordertable',
            name='DishAmount',
        ),
        migrations.AddField(
            model_name='table',
            name='CallingWaiter',
            field=models.BooleanField(default=False),
        ),
    ]
