# Generated by Django 3.2 on 2023-07-15 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230715_1320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dish',
            name='CostTime',
        ),
    ]
