# Generated by Django 3.2 on 2023-07-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20230724_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='DishImage',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
