# Generated by Django 3.2 on 2023-07-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_dish_dishimage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='DishImage',
        ),
        migrations.AddField(
            model_name='dish',
            name='DishImageURL',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
