# Generated by Django 4.2.1 on 2023-06-14 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_menu_delete_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-categoryName'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.RemoveField(
            model_name='menu',
            name='create_date',
        ),
        migrations.AlterField(
            model_name='menu',
            name='categoryName',
            field=models.CharField(db_index=True, max_length=50, verbose_name='categoryName (*)'),
        ),
    ]
